version: '3'
services:
  scan:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    privileged: true
    depends_on:
      - prometheus
    network_mode: "host"


  grafana:
    image: grafana/grafana
    volumes:
      - ./grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
      - scan
    restart: always
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=admin
    network_mode: "host"

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    restart: always
    network_mode: "host"


networks:
  scan:
    driver: bridge

