version: '3'
services:
  scan:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    privileged: true
    ports:
      - "8000:8000"
    depends_on:
      - prometheus
    networks:
      - scan


  grafana:
    image: grafana/grafana
    ports:
      - 4000:3000

    depends_on:
      - prometheus
      - scan
    restart: always
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_INSTALL_PLUGINS=
      - GF_PANEL_DEFAULT_URL=
    networks:
      - scan

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    restart: always
    networks:
      - scan


networks:
  scan:
    driver: bridge

